### ISSUE TITLE
关于如何新增一个动态tab页的疑问

### ISSUE THREAD

**Issue by botplayer0** [json-q/react-vite-admin#1]
你好，你的代码对我非常有用。
我本身没什么react基础，希望找一个模块能够快速使用并实现我需要的功能。
现在我卡在了如何新增一个动态tab页上，希望你能帮助到我。
前置:
在@/src/routes/index.tsx中配置路径/apitest/test。页面正常，tab正常，路由正常。
操作:
1. 前置/apitest/test中的children里添加/apitest/test/:id这种形式动态路由
2. 查看菜单
3. 点击菜单项
4. 直接访问/apitest/test/123
现象:
1. 动态路由被渲染在菜单中
2. 点击后会新增tab页，但是当前url变成/apitest/test/:id
3. 页面出现刷新的情况，丢失之前打开的tab页

**Comment by json-q** [comment]
问题出现的大致情况我理解了。
设计的时候确实没有考虑到动态路由这种情况。

问题原因：
因为展示的 tab 数据是缓存在 zustand 中的（可以使用redux调试工具查看数据），不是本地存储的，刷新页面必然会造成数据状态丢失（除了当前页，有页面加载时的逻辑处理），这个是比较麻烦的一点。

关于动态路由 tab 丢失：
可以尝试将 tab 的数据交给sessionStorage 管理，这种情况下刷新页面所有曾经打开过的 tab 项还会存在，但是页面缓存肯定是没有的（这种方式不太符合常规的设计，但可以作为临时解决方案）。

关于动态路由存在于 tab 中：
页面是否缓存是可以控制的，tab 项的展示也可以控制，这块的逻辑应该是在 menu 相关的文件里。可以在原基础上添加过滤的逻辑。

不在电脑前，暂时能想到的只有这么多，后续抽时间会完善一下动态路由相关的内容。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月09日 17:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [json-q/react-vite-admin] 关于如何新增一个动态tab页的疑问 (Issue #1) |

你好，你的代码对我非常有用。
我本身没什么react基础，希望找一个模块能够快速使用并实现我需要的功能。
现在我卡在了如何新增一个动态tab页上，希望你能帮助到我。
前置:
在@/src/routes/index.tsx中配置路径/apitest/test。页面正常，tab正常，路由正常。
操作:

前置/apitest/test中的children里添加/apitest/test/:id这种形式动态路由
查看菜单
点击菜单项
直接访问/apitest/test/123
现象:
动态路由被渲染在菜单中
点击后会新增tab页，但是当前url变成/apitest/test/:id
页面出现刷新的情况，丢失之前打开的tab页
